<?php

namespace AppBundle\Repository;

/**
 * DurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DurationRepository extends \Doctrine\ORM\EntityRepository
{
}
