<?php

namespace AppBundle\Repository;

/**
 * StammdatenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StammdatenRepository extends \Doctrine\ORM\EntityRepository
{
}
