<?php

namespace AppBundle\Repository;

/**
 * StdnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StdnRepository extends \Doctrine\ORM\EntityRepository
{
}
