<?php

namespace AppBundle\Repository;

/**
 * VertifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VertifRepository extends \Doctrine\ORM\EntityRepository
{
}
